-- UPDATE mysql.user SET Host='%' WHERE User='root';
-- FLUSH PRIVILEGES;
USE mysql;
CREATE USER 'root'@'%' IDENTIFIED BY '';
GRANT ALL ON *.* TO root@'%' IDENTIFIED BY '' WITH GRANT OPTION;
GRANT ALL ON *.* TO root@'localhost' IDENTIFIED BY '' WITH GRANT OPTION;
FLUSH PRIVILEGES;